-- Create appuser and set permissions
CREATE USER appuser WITH PASSWORD 'app@123';

GRANT CONNECT ON DATABASE department TO appuser;
GRANT CREATE ON SCHEMA public TO appuser;


GRANT USAGE ON SCHEMA public TO appuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO appuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appuser;
